export const techMap: {[key: string]: string} = {
    javascript: "devicon-javascript-plain",
    js : "devicon-javascript-plain",
    typescript: "devicon-typescript-plain",
    ts: "devicon-typescript-plain",
    react: "devicon-react-original",
    nextjs: "devicon-nextjs-original",
    node: "devicon-nodejs-plain",
    express: "devicon-express-original",
    mongodb: "devicon-mongodb-plain",
    mysql: "devicon-mysql-plain",
    postgresql: "devicon-postgresql-plain", 
    python: "devicon-python-plain",
    django: "devicon-django-plain",
    flask: "devicon-flask-original",
    ruby: "devicon-ruby-plain",
    rails: "devicon-rails-plain",
    php: "devicon-php-plain",
    laravel: "devicon-laravel-plain",
  }